// vue-code-block-themes/src/components/editor/examples/code-block-themes/theme-selector.vue
<script setup lang="ts">
import {
  defineCodeBlockShiki,
  shikiBundledThemesInfo,
  type ShikiBundledTheme,
} from 'prosekit/extensions/code-block'
import { useExtension } from 'prosekit/vue'
import { computed, ref } from 'vue'

const theme = ref<ShikiBundledTheme>('github-dark')
const extension = computed(() => {
  return defineCodeBlockShiki({ themes: [theme.value] })
})

useExtension(extension)
</script>

<template>
  <label for="code-block-theme-selector">Theme</label>
  <select
    id="code-block-theme-selector"
    v-model="theme"
    class="outline-unset focus-visible:outline-unset flex items-center justify-center rounded-md p-2 font-medium transition focus-visible:ring-2 text-sm focus-visible:ring-gray-900 dark:focus-visible:ring-gray-300 disabled:pointer-events-none min-w-9 min-h-9 text-gray-900 dark:text-gray-50 disabled:text-gray-900/50 dark:disabled:text-gray-50/50 bg-transparent hover:bg-gray-100 dark:hover:bg-gray-800 data-[state=on]:bg-gray-200 dark:data-[state=on]:bg-gray-700"
  >
    <option
      v-for="info in shikiBundledThemesInfo"
      :key="info.id"
      :value="info.id"
    >
      {{ info.id }}
    </option>
  </select>
</template>

// svelte-code-block-themes/src/components/editor/examples/code-block-themes/theme-selector.svelte
<script lang="ts">
import { defineCodeBlockShiki, shikiBundledThemesInfo, type ShikiBundledTheme } from 'prosekit/extensions/code-block'
import { useExtension } from 'prosekit/svelte'
import { toStore } from 'svelte/store'

let theme: ShikiBundledTheme = $state('github-dark')
let extension = $derived(defineCodeBlockShiki({ themes: [theme] }))

useExtension(toStore(() => extension))

function handleChange(event: Event) {
  const target = event.target as HTMLSelectElement
  theme = target.value as ShikiBundledTheme
}
</script>

<label for="code-block-theme-selector">Theme</label>
<select
  id="code-block-theme-selector"
  value={theme}
  onchange={handleChange}
  class="outline-unset focus-visible:outline-unset flex items-center justify-center rounded-md p-2 font-medium transition focus-visible:ring-2 text-sm focus-visible:ring-gray-900 dark:focus-visible:ring-gray-300 disabled:pointer-events-none min-w-9 min-h-9 text-gray-900 dark:text-gray-50 disabled:text-gray-900/50 dark:disabled:text-gray-50/50 bg-transparent hover:bg-gray-100 dark:hover:bg-gray-800 data-[state=on]:bg-gray-200 dark:data-[state=on]:bg-gray-700"
>
  {#each shikiBundledThemesInfo as info (info.id)}
    <option value={info.id}>
      {info.id}
    </option>
  {/each}
</select>
