// react-full/src/components/editor/ui/slash-menu/slash-menu-empty.tsx
import { AutocompleteEmpty } from 'prosekit/react/autocomplete'

export default function SlashMenuEmpty() {
  return (
    <AutocompleteEmpty className="relative flex items-center justify-between min-w-32 scroll-my-1 rounded-sm px-3 py-1.5 box-border cursor-default select-none whitespace-nowrap outline-hidden data-highlighted:bg-gray-100 dark:data-highlighted:bg-gray-800">
      <span>No results</span>
    </AutocompleteEmpty>
  )
}

// sveltekit-full/src/components/editor/ui/slash-menu/slash-menu-empty.svelte
<script lang="ts">
import { AutocompleteEmpty } from 'prosekit/svelte/autocomplete'
</script>

<AutocompleteEmpty class="relative flex items-center justify-between min-w-32 scroll-my-1 rounded-sm px-3 py-1.5 box-border cursor-default select-none whitespace-nowrap outline-hidden data-highlighted:bg-gray-100 dark:data-highlighted:bg-gray-800">
  <span>No results</span>
</AutocompleteEmpty>
