// vue-text-color/src/components/editor/examples/text-color/inline-menu.vue
<script setup lang="ts">
import type { Editor } from 'prosekit/core'
import { useEditorDerivedValue, useKeymap } from 'prosekit/vue'
import {
  InlinePopoverPopup,
  InlinePopoverPositioner,
  InlinePopoverRoot,
} from 'prosekit/vue/inline-popover'
import { ref } from 'vue'

import { Button } from '../../ui/button'

import type { EditorExtension } from './extension'

const textColors = [
  { label: 'Gray', value: '#9ca3af' },
  { label: 'Brown', value: '#92400e' },
  { label: 'Orange', value: '#ea580c' },
  { label: 'Yellow', value: '#ca8a04' },
  { label: 'Green', value: '#16a34a' },
  { label: 'Blue', value: '#2563eb' },
  { label: 'Purple', value: '#9333ea' },
  { label: 'Magenta', value: '#c026d3' },
  { label: 'Red', value: '#dc2626' },
]

const backgroundColors = [
  { label: 'Gray', value: '#f3f4f6' },
  { label: 'Brown', value: '#fef3c7' },
  { label: 'Orange', value: '#ffedd5' },
  { label: 'Yellow', value: '#fef9c3' },
  { label: 'Green', value: '#d1fae5' },
  { label: 'Blue', value: '#dbeafe' },
  { label: 'Purple', value: '#e9d5ff' },
  { label: 'Pink', value: '#fce7f3' },
  { label: 'Red', value: '#fecaca' },
]

function getTextColorState(editor: Editor<EditorExtension>) {
  return [
    {
      label: 'Default',
      value: 'currentColor',
      isActive: !editor.marks.textColor.isActive(),
      onClick: () => editor.commands.removeTextColor(),
    },
  ].concat(
    textColors.map((color) => ({
      label: color.label,
      value: color.value,
      isActive: editor.marks.textColor.isActive({ color: color.value }),
      onClick: () => editor.commands.addTextColor({ color: color.value }),
    })),
  )
}

function getBackgroundColorState(editor: Editor<EditorExtension>) {
  return [
    {
      label: 'Default',
      value: 'canvas',
      isActive: !editor.marks.backgroundColor.isActive(),
      onClick: () => editor.commands.removeBackgroundColor(),
    },
  ].concat(
    backgroundColors.map((color) => ({
      label: color.label,
      value: color.value,
      isActive: editor.marks.backgroundColor.isActive({ color: color.value }),
      onClick: () => editor.commands.addBackgroundColor({ color: color.value }),
    })),
  )
}

const textColorState = useEditorDerivedValue(getTextColorState)
const backgroundColorState = useEditorDerivedValue(getBackgroundColorState)
const open = ref(false)

useKeymap({
  Escape: () => {
    if (open.value) {
      open.value = false
      return true
    }
    return false
  },
})
</script>

<template>
  <InlinePopoverRoot
    :open="open"
    @open-change="(event) => (open = event.detail)"
  >
    <InlinePopoverPositioner
      class="block overflow-visible w-min h-min z-50 ease-out transition-transform duration-100 motion-reduce:transition-none"
    >
      <InlinePopoverPopup
        class="box-border origin-(--transform-origin) transition transition-discrete motion-reduce:transition-none data-[state=closed]:duration-150 data-[state=closed]:opacity-0 starting:opacity-0 data-[state=closed]:scale-95 starting:scale-95 duration-40 border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-950 shadow-lg relative flex min-w-32 space-x-1 overflow-auto whitespace-nowrap rounded-md p-1"
      >
        <div class="flex flex-col gap-4 p-4">
          <div class="flex flex-col gap-2">
            <div class="text-sm">Text color</div>
            <div class="grid grid-cols-5 gap-1">
              <Button
                v-for="color in textColorState"
                :key="color.label"
                :pressed="color.isActive"
                :tooltip="`Text: ${color.label}`"
                @click="color.onClick"
              >
                <span
                  class="text-base font-medium"
                  :style="{ color: color.value }"
                >
                  A
                </span>
              </Button>
            </div>
          </div>
          <div class="flex flex-col gap-2">
            <div class="text-sm">Background color</div>
            <div class="grid grid-cols-5 gap-1">
              <Button
                v-for="color in backgroundColorState"
                :key="color.label"
                :pressed="color.isActive"
                :tooltip="`Background: ${color.label}`"
                @click="color.onClick"
              >
                <div
                  class="w-6 h-6 rounded border border-gray-200 dark:border-gray-700"
                  :style="{ backgroundColor: color.value }"
                />
              </Button>
            </div>
          </div>
        </div>
      </InlinePopoverPopup>
    </InlinePopoverPositioner>
  </InlinePopoverRoot>
</template>

// svelte-text-color/src/components/editor/examples/text-color/inline-menu.svelte
<script lang="ts">
import type { Editor } from 'prosekit/core'
import { useEditorDerivedValue, useKeymap } from 'prosekit/svelte'
import { InlinePopoverPopup, InlinePopoverPositioner, InlinePopoverRoot } from 'prosekit/svelte/inline-popover'
import { toStore } from 'svelte/store'

import { Button } from '../../ui/button'

import type { EditorExtension } from './extension'

const textColors = [
  { label: 'Gray', value: '#9ca3af' },
  { label: 'Brown', value: '#92400e' },
  { label: 'Orange', value: '#ea580c' },
  { label: 'Yellow', value: '#ca8a04' },
  { label: 'Green', value: '#16a34a' },
  { label: 'Blue', value: '#2563eb' },
  { label: 'Purple', value: '#9333ea' },
  { label: 'Magenta', value: '#c026d3' },
  { label: 'Red', value: '#dc2626' },
]

const backgroundColors = [
  { label: 'Gray', value: '#f3f4f6' },
  { label: 'Brown', value: '#fef3c7' },
  { label: 'Orange', value: '#ffedd5' },
  { label: 'Yellow', value: '#fef9c3' },
  { label: 'Green', value: '#d1fae5' },
  { label: 'Blue', value: '#dbeafe' },
  { label: 'Purple', value: '#e9d5ff' },
  { label: 'Pink', value: '#fce7f3' },
  { label: 'Red', value: '#fecaca' },
]

function getTextColorState(editor: Editor<EditorExtension>) {
  return [{
    label: 'Default',
    value: 'currentColor',
    isActive: !editor.marks.textColor.isActive(),
    onClick: () => editor.commands.removeTextColor(),
  }].concat(textColors.map((color) => ({
    label: color.label,
    value: color.value,
    isActive: editor.marks.textColor.isActive({ color: color.value }),
    onClick: () => editor.commands.addTextColor({ color: color.value }),
  })))
}

function getBackgroundColorState(editor: Editor<EditorExtension>) {
  return [{
    label: 'Default',
    value: 'canvas',
    isActive: !editor.marks.backgroundColor.isActive(),
    onClick: () => editor.commands.removeBackgroundColor(),
  }].concat(
    backgroundColors.map((color) => ({
      label: color.label,
      value: color.value,
      isActive: editor.marks.backgroundColor.isActive({ color: color.value }),
      onClick: () => editor.commands.addBackgroundColor({ color: color.value }),
    })),
  )
}

const textColorState = useEditorDerivedValue(getTextColorState)
const backgroundColorState = useEditorDerivedValue(getBackgroundColorState)

let open = $state(false)

const keymap = $derived({
  Escape: () => {
    if (open) {
      open = false
      return true
    }
    return false
  },
})

useKeymap(toStore(() => keymap))
</script>

<InlinePopoverRoot
  {open}
  onOpenChange={(event) => open = event.detail}
>
  <InlinePopoverPositioner class="block overflow-visible w-min h-min z-50 ease-out transition-transform duration-100 motion-reduce:transition-none">
    <InlinePopoverPopup class="box-border origin-(--transform-origin) transition transition-discrete motion-reduce:transition-none data-[state=closed]:duration-150 data-[state=closed]:opacity-0 starting:opacity-0 data-[state=closed]:scale-95 starting:scale-95 duration-40 border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-950 shadow-lg relative flex min-w-32 space-x-1 overflow-auto whitespace-nowrap rounded-md p-1">
      <div class="flex flex-col gap-4 p-4">
        <div class="flex flex-col gap-2">
          <div class="text-sm">Text color</div>
          <div class="grid grid-cols-5 gap-1">
            {#each $textColorState as color (color.label)}
              <Button
                pressed={color.isActive}
                tooltip={`Text: ${color.label}`}
                onClick={color.onClick}
              >
                <span class="text-base font-medium" style:color={color.value}>
                  A
                </span>
              </Button>
            {/each}
          </div>
        </div>
        <div class="flex flex-col gap-2">
          <div class="text-sm">Background color</div>
          <div class="grid grid-cols-5 gap-1">
            {#each $backgroundColorState as color (color.label)}
              <Button
                pressed={color.isActive}
                tooltip={`Background: ${color.label}`}
                onClick={color.onClick}
              >
                <div
                  class="w-6 h-6 rounded border border-gray-200 dark:border-gray-700"
                  style:background-color={color.value}
                >
                </div>
              </Button>
            {/each}
          </div>
        </div>
      </div>
    </InlinePopoverPopup>
  </InlinePopoverPositioner>
</InlinePopoverRoot>
