// vue-tweet/src/components/editor/examples/tweet/tweet-view.vue
<script setup lang="ts">
import type { VueNodeViewProps } from 'prosekit/vue'
import Tweet from 'vue-tweet'

const props = defineProps<VueNodeViewProps>()

const tweetId = props.node.value.attrs.tweetId as string
</script>

<template>
  <div>
    <div>
      <strong>
        Rendered in Vue using library
        <span>
          <a
            href="https://github.com/DannyFeliz/vue-tweet"
            target="_blank"
            rel="noopener noreferrer"
          >
            vue-tweet
          </a>
        </span>
      </strong>
    </div>
    <Tweet :tweet-id="tweetId" />
  </div>
</template>

// react-tweet/src/components/editor/examples/tweet/tweet-view.tsx
import type { ReactNodeViewProps } from 'prosekit/react'
import { Tweet } from 'react-tweet'

export function TweetView({ node }: ReactNodeViewProps) {
  const tweetId = node.attrs.tweetId as string
  return (
    <div className="[&_img]:m-0!">
      <div>
        <strong>
          Rendered in React using library{' '}
          <span>
            <a
              href="https://github.com/vercel/react-tweet"
              target="_blank"
              rel="noopener noreferrer"
            >
              react-tweet
            </a>
          </span>
        </strong>
      </div>
      <Tweet id={tweetId} />
    </div>
  )
}
