// vue-text-color/src/inline-menu.vue
<script setup lang="ts">
import { useEditor, useKeymap } from 'prosekit/vue'
import { InlinePopover } from 'prosekit/vue/inline-popover'
import { ref } from 'vue'

import Button from './button.vue'
import type { EditorExtension } from './extension'

const editor = useEditor<EditorExtension>({ update: true })
const colors = [
  { name: 'default', value: '' },
  { name: 'red', value: '#ef4444' },
  { name: 'orange', value: '#f97316' },
  { name: 'yellow', value: '#eab308' },
  { name: 'green', value: '#22c55e' },
  { name: 'blue', value: '#3b82f6' },
  { name: 'indigo', value: '#6366f1' },
  { name: 'violet', value: '#a855f7' },
]

function hasTextColor(color: string) {
  return editor.value.marks.textColor.isActive({ color })
}

function toggleTextColor(color: string) {
  if (!color || hasTextColor(color)) {
    editor.value.commands.removeTextColor()
  } else {
    editor.value.commands.setTextColor({ color })
  }
}

const open = ref(false)
function onOpenChange(value: boolean) {
  open.value = value
}

function onEscape() {
  if (open.value) {
    open.value = false
    return true
  }
  return false
}

useKeymap({ Escape: onEscape })
</script>

<template>
  <InlinePopover
    class="z-10 box-border border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-950 shadow-lg [&:not([data-state])]:hidden relative flex min-w-[8rem] space-x-1 overflow-auto whitespace-nowrap rounded-md p-1"
    :open="open"
    @open-change="onOpenChange"
  >
    <Button
      v-for="color in colors"
      :key="color.name"
      :pressed="hasTextColor(color.value)"
      :tooltip="color.name"
      @click="() => toggleTextColor(color.value)"
    >
      <span :style="{ color: color.value }">A</span>
    </Button>
  </InlinePopover>
</template>

// react-text-color/src/inline-menu.tsx
import type { Editor } from 'prosekit/core'
import { useEditor, useEditorDerivedValue, useKeymap } from 'prosekit/react'
import { InlinePopover } from 'prosekit/react/inline-popover'
import { useState } from 'react'

import Button from './button'
import type { EditorExtension } from './extension'

const colors = [
  { name: 'default', value: '' },
  { name: 'red', value: '#ef4444' },
  { name: 'orange', value: '#f97316' },
  { name: 'yellow', value: '#eab308' },
  { name: 'green', value: '#22c55e' },
  { name: 'blue', value: '#3b82f6' },
  { name: 'indigo', value: '#6366f1' },
  { name: 'violet', value: '#a855f7' },
]

function hasTextColor(editor: Editor<EditorExtension>, color: string) {
  return editor.marks.textColor.isActive({ color })
}

function getColorState(editor: Editor<EditorExtension>) {
  return colors.map((color) => ({
    name: color.name,
    value: color.value,
    isActive: hasTextColor(editor, color.value),
  }))
}

export default function InlineMenu() {
  const editor = useEditor<EditorExtension>()
  const colorState = useEditorDerivedValue(getColorState)
  const [open, setOpen] = useState(false)

  const toggleTextColor = (color: string) => {
    if (!color || hasTextColor(editor, color)) {
      editor.commands.removeTextColor()
    } else {
      editor.commands.setTextColor({ color })
    }
  }

  useKeymap({
    Escape: () => {
      if (open) {
        setOpen(false)
        return true
      }
      return false
    },
  })

  return (
    <InlinePopover
      className="z-10 box-border border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-950 shadow-lg [&:not([data-state])]:hidden relative flex min-w-32 space-x-1 overflow-auto whitespace-nowrap rounded-md p-1"
      open={open}
      onOpenChange={setOpen}
    >
      {colorState.map((color) => (
        <Button
          key={color.name}
          pressed={color.isActive}
          tooltip={color.name}
          onClick={() => toggleTextColor(color.value)}
        >
          <span style={{ color: color.value }}>A</span>
        </Button>
      ))}
    </InlinePopover>
  )
}
