// vue-text-align/src/components/editor/examples/text-align/toolbar.vue
<script setup lang="ts">
import type { Editor } from 'prosekit/core'
import { useEditorDerivedValue } from 'prosekit/vue'

import { Button } from '../../ui/button'

import type { EditorExtension } from './extension'

function isTextAlignActive(editor: Editor<EditorExtension>, value: string) {
  return Object.values(editor.nodes).some((node) => {
    // @ts-expect-error textAlign may not be available on every node
    return node.isActive({ textAlign: value })
  })
}

function getToolbarItems(editor: Editor<EditorExtension>) {
  return {
    left: {
      isActive: isTextAlignActive(editor, 'left'),
      canExec: editor.commands.setTextAlign.canExec('left'),
      command: () => editor.commands.setTextAlign('left'),
    },
    center: {
      isActive: isTextAlignActive(editor, 'center'),
      canExec: editor.commands.setTextAlign.canExec('center'),
      command: () => editor.commands.setTextAlign('center'),
    },
    right: {
      isActive: isTextAlignActive(editor, 'right'),
      canExec: editor.commands.setTextAlign.canExec('right'),
      command: () => editor.commands.setTextAlign('right'),
    },
    justify: {
      isActive: isTextAlignActive(editor, 'justify'),
      canExec: editor.commands.setTextAlign.canExec('justify'),
      command: () => editor.commands.setTextAlign('justify'),
    },
  }
}

const items = useEditorDerivedValue(getToolbarItems)
</script>

<template>
  <div
    class="z-2 box-border border-gray-200 dark:border-gray-800 border-solid border-l-0 border-r-0 border-t-0 border-b flex flex-wrap gap-1 p-2 items-center"
  >
    <Button
      :pressed="items.left.isActive"
      :disabled="!items.left.canExec"
      @click="items.left.command"
    >
      Left
    </Button>

    <Button
      :pressed="items.center.isActive"
      :disabled="!items.center.canExec"
      @click="items.center.command"
    >
      Center
    </Button>

    <Button
      :pressed="items.right.isActive"
      :disabled="!items.right.canExec"
      @click="items.right.command"
    >
      Right
    </Button>

    <Button
      :pressed="items.justify.isActive"
      :disabled="!items.justify.canExec"
      @click="items.justify.command"
    >
      Justify
    </Button>
  </div>
</template>

// svelte-text-align/src/toolbar.svelte
<script lang="ts">
import type {
  Editor,
  NodeAction,
} from 'prosekit/core'
import { useEditor } from 'prosekit/svelte'
import Button from './button.svelte'
import type { EditorExtension } from './extension'

const editor = useEditor<EditorExtension>({ update: true })

const isTextAlignActive = (editor: Editor<EditorExtension>, value: string) => {
  return Object.values(editor.nodes).some((node: NodeAction<any>) => {
    return node.isActive({ textAlign: value })
  })
}
</script>

<div class='z-2 box-border border-gray-200 dark:border-gray-800 border-solid border-l-0 border-r-0 border-t-0 border-b flex flex-wrap gap-1 p-2 items-center'>
  <Button
    pressed={isTextAlignActive($editor, 'left')}
    disabled={!$editor.commands.setTextAlign.canExec('left')}
    onClick={() => $editor.commands.setTextAlign('left')}
  >
    Left
  </Button>

  <Button
    pressed={isTextAlignActive($editor, 'center')}
    disabled={!$editor.commands.setTextAlign.canExec('center')}
    onClick={() => $editor.commands.setTextAlign('center')}
  >
    Center
  </Button>

  <Button
    pressed={isTextAlignActive($editor, 'right')}
    disabled={!$editor.commands.setTextAlign.canExec('right')}
    onClick={() => $editor.commands.setTextAlign('right')}
  >
    Right
  </Button>

  <Button
    pressed={isTextAlignActive($editor, 'justify')}
    disabled={!$editor.commands.setTextAlign.canExec('justify')}
    onClick={() => $editor.commands.setTextAlign('justify')}
  >
    Justify
  </Button>
</div>
