// svelte-slash-menu/src/slash-menu-item.svelte
<script lang="ts">
import { AutocompleteItem } from 'prosekit/svelte/autocomplete'

export let onSelect: () => void
export let label: string
export let kbd: string | undefined = undefined
</script>

<AutocompleteItem {onSelect} class="relative flex items-center justify-between min-w-32 scroll-my-1 rounded-sm px-3 py-1.5 box-border cursor-default select-none whitespace-nowrap outline-hidden data-[focused]:bg-gray-100 dark:data-[focused]:bg-gray-800">
  <span>{label}</span>
  {#if kbd}
    <kbd class="text-xs font-mono text-gray-400 dark:text-gray-500">{kbd}</kbd>
  {/if}
</AutocompleteItem>

// next-full/components/editor/ui/slash-menu/slash-menu-item.tsx
import { AutocompleteItem } from 'prosekit/react/autocomplete'

export default function SlashMenuItem(props: {
  label: string
  kbd?: string
  onSelect: () => void
}) {
  return (
    <AutocompleteItem
      onSelect={props.onSelect}
      className="relative flex items-center justify-between min-w-32 scroll-my-1 rounded-sm px-3 py-1.5 box-border cursor-default select-none whitespace-nowrap outline-hidden data-focused:bg-gray-100 dark:data-focused:bg-gray-800"
    >
      <span>{props.label}</span>
      {props.kbd && (
        <kbd className="text-xs font-mono text-gray-400 dark:text-gray-500">
          {props.kbd}
        </kbd>
      )}
    </AutocompleteItem>
  )
}
