// svelte-full/src/slash-menu-empty.svelte
<script lang="ts">
import { AutocompleteEmpty } from 'prosekit/svelte/autocomplete'
</script>

<AutocompleteEmpty class="relative flex items-center justify-between min-w-32 scroll-my-1 rounded-sm px-3 py-1.5 box-border cursor-default select-none whitespace-nowrap outline-hidden data-[focused]:bg-gray-100 dark:data-[focused]:bg-gray-800">
  <span>No results</span>
</AutocompleteEmpty>

// vue-rtl/src/components/editor/ui/slash-menu/slash-menu-empty.vue
<script setup lang="ts">
import { AutocompleteEmpty } from 'prosekit/vue/autocomplete'
</script>

<template>
  <AutocompleteEmpty
    class="relative flex items-center justify-between min-w-32 scroll-my-1 rounded-sm px-3 py-1.5 box-border cursor-default select-none whitespace-nowrap outline-hidden data-focused:bg-gray-100 dark:data-focused:bg-gray-800"
  >
    <span>No results</span>
  </AutocompleteEmpty>
</template>
