// vue-unmount/src/extension-component.vue
<script setup lang="ts">
import { definePlaceholder } from 'prosekit/extensions/placeholder'
import { useExtension } from 'prosekit/vue'
import { computed } from 'vue'

const props = defineProps<{ placeholder: string }>()

const extension = computed(() =>
  definePlaceholder({ placeholder: props.placeholder }),
)

useExtension(extension)
</script>

<!-- eslint-disable-next-line vue/valid-template-root -->
<template>
  <!-- Empty template to avoid Vue warning "Component is missing template or render function" -->
</template>

// preact-unmount/src/components/editor/examples/unmount/extension-component.tsx
import { useMemo } from 'preact/hooks'
import { definePlaceholder } from 'prosekit/extensions/placeholder'
import { useExtension } from 'prosekit/preact'

export default function ExtensionComponent(props: { placeholder: string }) {
  const extension = useMemo(
    () => definePlaceholder({ placeholder: props.placeholder }),
    [props.placeholder],
  )

  useExtension(extension)

  return null
}
