// react-code-block-themes/src/components/editor/examples/code-block-themes/toolbar.tsx
'use client'

import { ThemeSelector } from './theme-selector'

export default function Toolbar() {
  return (
    <div className="z-2 box-border border-gray-200 dark:border-gray-800 border-solid border-l-0 border-r-0 border-t-0 border-b flex flex-wrap gap-1 p-2 items-center">
      <ThemeSelector />
    </div>
  )
}

// solid-readonly/src/components/editor/examples/readonly/toolbar.tsx
import type { JSX } from 'solid-js'

import { Button } from '../../ui/button'

import { useReadonly } from './use-readonly'

export default function Toolbar(): JSX.Element {
  const { readonly, setReadonly } = useReadonly()

  return (
    <div class="z-2 box-border border-gray-200 dark:border-gray-800 border-solid border-l-0 border-r-0 border-t-0 border-b flex flex-wrap gap-1 p-2 items-center">
      <Button pressed={readonly()} onClick={() => setReadonly(true)}>
        Readonly
      </Button>

      <Button pressed={!readonly()} onClick={() => setReadonly(false)}>
        Editable
      </Button>
    </div>
  )
}
